### ISSUE TITLE
'NoneType' object has no attribute '_meta when applying migrations with router

### ISSUE THREAD

**Issue by GigiusB** [Opus10/django-pgtrigger#44] opened 2021-11-09 13:52 UTC
I am using [django-database-for-apps](https://pypi.org/project/django-database-for-apps/) for automatically routing apps on schemas.
When migrating I have the following error:

```
.../python3.9/site-packages/django_database_for_apps/__init__.py", line 15, in db_for_write
    return getattr(settings, 'DATABASE_FOR_APPS', {}).get(model._meta.app_label, getattr(settings, 'DATABASE_FOR_APPS', {}).get('*', 'default'))
AttributeError: 'NoneType' object has no attribute '_meta'
```

I believe the method pgtrigger.core._get_model should use pgtrigger.core._get_database

**Comment by wesleykendall** [comment] 2022-07-30 23:06
@GigiusB I was going through the app you linked and got lost trying to reproduce the error.

It sounds like you are using schemas with your tables, which might also be causing some issues.

Can you post some psuedocode of your models and the database-for-apps config you have? I have some multiple DB test cases that use routers, so perhaps I can reproduce it

**Comment by wesleykendall** [comment] 2022-08-10 04:08
@GigiusB I think I understand your issue better now after going through https://github.com/Opus10/django-pgtrigger/issues/54

Good news is that version 3 should solve this issue because triggers are now integrated with the django migration system. As noted in https://github.com/Opus10/django-pgtrigger/issues/54, the issue you ran into was part of the legacy system

Going to still see if I can get your fix in

**Comment by wesleykendall** [comment] 2022-08-14 03:02
@GigiusB this bug is fixed in https://github.com/Opus10/django-pgtrigger/pull/80

See the response on #54 about how multi-schema setup works. There will be a new section in the docs for it once the latest release is deployed.

Since you are using a different DB per schema, you should be able to use the multi-db support. I.e. the ``--database`` option to the management commands should work, and migrating triggers in the migration system will respect the ``--database`` option supplied to ``manage.py migrate``.

Will let you know when it's released

**Comment by wesleykendall** [comment] 2022-08-15 04:44
Fixed in version 4

**Closed by wesleykendall** 2022-08-15 04:44 UTC
Labels: bug
