### ISSUE TITLE
IntegrityError with pgtrigger Soft Delete When Cascading Deletions

### ISSUE THREAD

**Issue by helgi-empower** [Opus10/django-pgtrigger#151] opened 2024-03-22 17:01 UTC
I am encountering an IntegrityError while trying to implement a soft delete mechanism using pgtrigger in my Django models. This error occurs when I attempt to delete an instance of a related model (model B in the example below). I am unsure if this is expected behaviour and I am misunderstanding the documentation. Below is a simplified version of my models to illustrate the setup:

```python
from django.db import models
import pgtrigger

class B(models.Model):
    value = models.IntegerField(default=10)

class A(models.Model):
    b = models.ForeignKey(B, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    class Meta:
        triggers = [
            pgtrigger.SoftDelete(
                name='soft_delete',
                field='is_active',
                value=False,
            ),
        ]

# to reproduce the error:
# create an instances of B and A
b = B.objects.create()
a = A.objects.create(b=b)

# try to delete b
b.delete()  # 💥 this raises an error like IntegrityError: update or delete on table "related_model" violates foreign key constraint "fk_constraint_name" on table "primary_model"
```

Any advice or solutions would be highly appreciated. Thanks in advance for your support!

**Comment by wesleykendall** [comment] 2024-08-26 13:49
This is expected behavior. When model `b` is deleted, Django cascade deletes `a`, however, `a` isn't actually deleted from the DB, but rather soft-deleted. Because of this `a` still references `b`, leading to a foreign key conflict when the transaction is committed since `b` was hard deleted.

It depends on what you are trying to accomplish in your app, but there are a few ways around this:

1. Don't hard delete B. Consider making it soft-deletable
2. Set the foreign key to be nullable and use `SET_NULL` as the cascading behavior
3. Use a different soft-deletion approach altogether. For example, allow hard-deletes of `A`, but use [django-pghistory](https://github.com/Opus10/django-pghistory) to snapshot it as it's deleted

Again, all depends on the application context. The crux of the issue is that A, a soft-deleted model, maintains a foreign key to B, a model that is hard-deleted, and the foreign key is not nullable

**Closed by wesleykendall** 2024-08-26 13:49 UTC
Labels: question
